/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mogus.transferlistaORM.view;

import javax.swing.JOptionPane;
import mogus.transferlistaORM.controller.ObradaOperater;
import mogus.transferlistaORM.model.Operater;

/**
 *
 * @author domin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLozinka = new javax.swing.JPasswordField();
        btnLogiraj = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 50, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtEmail.setText("mogusd97@gmail.com");
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Lozinka");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 110, 20));

        txtLozinka.setText("t");
        getContentPane().add(txtLozinka, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 210, -1));

        btnLogiraj.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLogiraj.setText("Logiraj se");
        btnLogiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogirajActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogiraj, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 140, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mogus/transferlistaORM/view/login.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogirajActionPerformed
        ObradaOperater oo = new ObradaOperater();
        Operater o = oo.autoriziraj(txtEmail.getText(), String.valueOf(txtLozinka.getPassword()));
        if(o!=null){
            new Izbornik(o).setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Neispravan email kombinacija email i lozinka");
        }
    }//GEN-LAST:event_btnLogirajActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogiraj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtLozinka;
    // End of variables declaration//GEN-END:variables
}
